version: '3'

services:
  kafka:
    image: confluentinc/cp-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "192.168.0.103:2182"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://192.168.0.103:9092"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
